### ISSUE TITLE
Use textureGatherOffset for performance

### ISSUE THREAD

**Issue by haasn** [bjin/mpv-prescalers#7]
`textureGatherOffset` can be used to gather a single component of four adjacent pixels at the same time. This seems ideal for NNEDI3, which basically samples a single component of entire 8x4 window area - this can be collapsed down to eight `textureGatherOffset` calls instead of 8*4 `texture()[0]` calls.

You can use it like this:

Instead of:

```
vec4 color;
color.x = textureOffset(tex, pos, ivec2(0, 1))[n];
color.y = textureOffset(tex, pos, ivec2(1, 1))[n];
color.z = textureOffset(tex, pos, ivec2(1, 0))[n];
color.w = textureOffset(tex, pos, ivec2(0, 0))[n];
```

You can do this:
```
vec4 color = textureGatherOffset(tex, pos, ivec2(0, 0), n);
```

Please note that the samples are returned starting from the bottom left pixel going counter-clockwise. You also need a new enough version of mpv to take advantage of GLSL 400. (It was previously clamped to 330 for deprecated reasons).

**Comment by bjin** [comment]
Did a quick look. The user shaders currently uses `HOOKED_texOff` macro, which eventually calls `texture()`. I'm fine dealing with `HOOKED_raw` directly, but the missing pieces seems to be `tex.multiplier` used by `HOOKED_tex` macro. Do you know any workaround?

**Comment by haasn** [comment]
Hmm, nope. I could add a solution for that in mpv but first I would like to know whether it benefits performance or not, and if so, by how much.

**Comment by bjin** [comment]
There is significant improvements. I tested with Intel card on an early 2015 macbook pro, doubling 720p with `16` neurons and `8x4` window. The render time for second pass decreased from `31.3ms` to `27.5ms`, roughly 12%. I don't have nVidia/AMD card for testing at this moment, but I guess the improvement will be larger.

I think it's due to the fact that four `texture()` calls could be replaced with a single `textureGatherOffset()` call, if only the luma plane is involved.

Although it's a non-trivial change:
* `textureGatherOffset` requires component number to be constant, so I had to refactor the whole process to remove `comp` as variable.
* The coordinate calculation becomes rather complicated. To the point that it's meaningless to reserve an option to generate shader without use of `textureGatherOffset` (they can be retrieved from old commits anyway).

**Comment by haasn** [comment]
Tested GTX 970 with 1080p content, luma only, 16 NNs:

`nnedi3-direct.glsl`: 3.5ms + 7.0ms = 10.5ms
`nnedi3-gather.glsl`: 3.4ms + 6.8ms = 10.2ms

So it's an improvement, but not massive. In retrospect, not too surprising, considering the bulk of the work for nnedi3 is computational in nature (calculating all of those neuron connections).

**Comment by haasn** [comment]
I've exposed `NAME_mul` in https://github.com/mpv-player/mpv/commit/aa2bdec26cf2544cffa4b2613086f226127e2ea8

Note that as long as your operations are linear, this means you can also delay multiplying in the coefficient until the first nonlinear step - potentially saving a few mul instructions.

**Comment by bjin** [comment]
I see. I thought that with nVidia/AMD card, the computation part (basically just bunch of vector dot multiplications) is faster. But it seems to be the other way.

> I've exposed NAME_mul in mpv-player/mpv@aa2bdec

Thanks!

**Comment by haasn** [comment]
@bjin It could also just be the case that texture sampling on intel is slower.
